Repository PinkDumbbell/CocoBob-BE, pull requests merged in 2022-11, with the labels that each got.

#89 CB 508 클라이언트에서 이미지 압축하여 보내야 함
  src/main/java/com/pinkdumbell/cocobob/domain/product/Product.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/dto/ProductDetailResponseDto.java
  src/main/resources/db/migration/V16__alter_product_table.sql
Labels: refactor, chore

#88 CB 430 BE 테스트 커버리지 측정이 필요함
  build.gradle
  src/main/java/com/pinkdumbell/cocobob/domain/product/Product.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/ProductController.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/dto/ProductDetailResponseDto.java
  src/main/resources/db/migration/V16__alter_product_table.sql
  src/test/java/com/pinkdumbell/cocobob/domain/product/ProductControllerTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/product/ProductRepositoryTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/product/ProductServiceTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/user/UserRepositoryTest.java
Labels: test, chore

#90 [CB-520] [BE] 최근 7개의 몸무게를 불러올 때 null이 반환됨
  src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/HealthRecordRepository.java
  src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/dto/RecentWeightsResponseDto.java
Labels: fix

#91 [CB-530] [BE] 식사 기록을 생성할 때 건강 기록이 생성되어 있지 않으면 생성할 수 없음
  src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/HealthRecordController.java
  src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/HealthRecordResponseClass.java
  src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/HealthRecordService.java
  src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/dto/HealthRecordCreateResponseDto.java
Labels: refactor

#92 [CB-539] [BE] 건강 기록 급여기록 리스폰스에서 급여 사료의 정보가 부족함
  src/main/java/com/pinkdumbell/cocobob/domain/product/ProductRepository.java
  src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/dto/HealthRecordDetailResponseDto.java
Labels: refactor, fix

#93 개발 서버와 배포 서버 동기화 작업
  build.gradle
  src/main/java/com/pinkdumbell/cocobob/common/apilog/ApiLog.java
  src/main/java/com/pinkdumbell/cocobob/common/apilog/ApiLogInterceptor.java
  src/main/java/com/pinkdumbell/cocobob/common/apilog/ApiLogRepository.java
  src/main/java/com/pinkdumbell/cocobob/config/WebConfig.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/Product.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/ProductController.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/ProductRepository.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/dto/ProductDetailResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/HealthRecordController.java
  src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/HealthRecordRepository.java
  src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/HealthRecordResponseClass.java
  src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/HealthRecordService.java
  src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/dto/HealthRecordCreateResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/dto/HealthRecordDetailResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/dto/RecentWeightsPerDatesDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/dto/RecentWeightsResponseDto.java
  src/main/resources/db/migration/V15__create_api_log.sql
  src/main/resources/db/migration/V16__alter_product_table.sql
  src/test/java/com/pinkdumbell/cocobob/domain/pet/PetControllerTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/product/ProductControllerTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/product/ProductRepositoryTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/product/ProductServiceTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/record/healthrecord/HealthRecordRepositoryTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/user/UserControllerUnitTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/user/UserRepositoryTest.java
Labels: test, fix, feat, chore

#94 [CB-549] [BE] 반려동물의 나이가 시간에 따라 바뀌어야 함
  src/main/java/com/pinkdumbell/cocobob/domain/pet/PetService.java
  src/main/resources/db/migration/V17__add_event_scheduler_pet_age_update.sql
Labels: feat

#95 [CB-564] [BE] 오류 로그를 확인하기 어려움
  build.gradle
  src/main/java/com/pinkdumbell/cocobob/common/SlackService.java
  src/main/java/com/pinkdumbell/cocobob/exception/GlobalExceptionHandler.java
  src/main/resources/application-secret.yml.gpg
Labels: feat, chore

#96 dev to main merge
  build.gradle
  src/main/java/com/pinkdumbell/cocobob/common/SlackService.java
  src/main/java/com/pinkdumbell/cocobob/exception/GlobalExceptionHandler.java
  src/main/resources/application-secret.yml.gpg
  src/main/resources/db/migration/V17__add_event_scheduler_pet_age_update.sql
  src/test/java/com/pinkdumbell/cocobob/CocobobApplicationTests.java
  src/test/java/com/pinkdumbell/cocobob/domain/pet/PetControllerTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/product/ProductControllerTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/user/UserControllerTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/user/UserControllerUnitTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/user/UserServiceTest.java
Labels: chore
