Repository PinkDumbbell/CocoBob-BE, pull requests merged in 2022-07, with the labels that each got.

#5 CB-10 RDS 서버 환경 구축
  .DS_Store
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/pinkdumbell/cocobob/CocobobApplication.java
  src/main/resources/application.yml
  src/test/java/com/pinkdumbell/cocobob/CocobobApplicationTests.java
Labels: chore

#9 CB-117-swagger-설정이-필요함
  build.gradle
  src/main/java/com/pinkdumbell/cocobob/ProfileController.java
  src/main/java/com/pinkdumbell/cocobob/config/SwaggerConfig.java
Labels: chore

#10 CB-91 be 자체로그인
  build.gradle
  src/main/java/com/pinkdumbell/cocobob/config/WebConfig.java
  src/main/java/com/pinkdumbell/cocobob/domain/auth/Token.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/User.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/UserController.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/UserRepository.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/UserRole.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/UserService.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/dto/EmailDuplicationCheckResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/dto/UserCreateRequestDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/dto/UserCreateResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/exception/CustomException.java
  src/main/java/com/pinkdumbell/cocobob/exception/ErrorCode.java
  src/main/java/com/pinkdumbell/cocobob/exception/ErrorResponse.java
  src/main/java/com/pinkdumbell/cocobob/exception/GlobalExceptionHandler.java
  src/test/java/com/pinkdumbell/cocobob/domain/user/UserServiceTest.java
  src/test/resources/application.yml
Labels: refactor, fix, feat, chore

#13 Cb 146 be 로그인 api가 없음
  build.gradle
  src/test/java/com/pinkdumbell/cocobob/domain/user/UserServiceTest.java
  src/test/resources/application.yml
Labels: fix, feat, chore

#14 CB-133 [BE] flyway를 활용하여 쿼리 분리가 필요함
  build.gradle
  src/main/resources/application-real1.yml
  src/main/resources/application-real2.yml
  src/main/resources/application-setting.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/V1__empty.sql
  src/test/resources/application.yml
Labels: chore

#15 Cb 157 리프레시 토큰이 없음
  .github/workflows/deploy.yaml
  build.gradle
  src/main/java/com/pinkdumbell/cocobob/config/SecurityConfig.java
  src/main/java/com/pinkdumbell/cocobob/domain/auth/JwtTokenProvider.java
  src/main/java/com/pinkdumbell/cocobob/domain/auth/Token.java
  src/main/java/com/pinkdumbell/cocobob/domain/auth/TokenRepository.java
  src/main/java/com/pinkdumbell/cocobob/domain/auth/UserDetail.java
  src/main/java/com/pinkdumbell/cocobob/domain/auth/dto/JwtExceptionResponse.java
  src/main/java/com/pinkdumbell/cocobob/domain/auth/dto/TokenRequestDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/auth/dto/TokenResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/pinkdumbell/cocobob/domain/auth/filter/JwtExceptionFilter.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/User.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/UserController.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/UserService.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/dto/UserLoginRequestDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/dto/UserLoginResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/exception/ErrorCode.java
  src/test/java/com/pinkdumbell/cocobob/domain/user/UserControllerTest.java
  src/test/resources/application.yml
Labels: test, refactor, feat, chore

#17 CB-158-[BE] DB 스키마에 상응하는 엔터티가 생성되지 않음
  src/main/java/com/pinkdumbell/cocobob/domain/abnormal/Abnormal.java
  src/main/java/com/pinkdumbell/cocobob/domain/allergy/Allergy.java
  src/main/java/com/pinkdumbell/cocobob/domain/daily/Daily.java
  src/main/java/com/pinkdumbell/cocobob/domain/daily/abnormal/DailyAbnormal.java
  src/main/java/com/pinkdumbell/cocobob/domain/daily/abnormal/DailyAbnormalId.java
  src/main/java/com/pinkdumbell/cocobob/domain/daily/image/DailyImage.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/Pet.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/allergy/PetAllergy.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/allergy/PetAllergyId.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/breed/Breed.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/dailypattern/DailyPattern.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/image/PetImage.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/problem/PetProblem.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/problem/PetProblemId.java
  src/main/java/com/pinkdumbell/cocobob/domain/problem/Problem.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/Product.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/description/ProductDescriptionImage.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/image/ProductImage.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/ingredient/Ingredient.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/like/Like.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/like/LikeId.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/nutrition/Nutrition.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/problem/ProductProblem.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/problem/ProductProblemId.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/review/Review.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/review/image/ReviewImage.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/AccountType.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/User.java
Labels: fix, feat

#18 CB-97 [feat]: add https address
  src/main/java/com/pinkdumbell/cocobob/config/WebConfig.java
Labels: feat, chore

#19 CB-185 [refactor]: modify wrong context error message
  src/main/java/com/pinkdumbell/cocobob/exception/ErrorCode.java
Labels: fix

#20 [CB-128] [BE] 반려동물 등록 api 필요함
  build.gradle
  src/main/java/com/pinkdumbell/cocobob/CocobobApplication.java
  src/main/java/com/pinkdumbell/cocobob/domain/common/AwsS3Service.java
  src/main/java/com/pinkdumbell/cocobob/domain/common/ImageService.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/Pet.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/PetController.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/PetRepository.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/PetService.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/PetSex.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/breed/Breed.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/breed/BreedRepository.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/breed/BreedSize.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/dto/PetCreateRequestDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/dto/PetCreateResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/image/PetImage.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/image/PetImageRepository.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/UserService.java
  src/main/java/com/pinkdumbell/cocobob/exception/ErrorCode.java
  src/main/java/com/pinkdumbell/cocobob/exception/ErrorResponse.java
  src/main/java/com/pinkdumbell/cocobob/exception/GlobalExceptionHandler.java
  src/main/resources/application-setting.yml
  src/main/resources/db/migration/V1__empty.sql
  src/main/resources/db/migration/V1__init.sql
  src/main/resources/db/migration/V2__insert_breed.sql
  src/test/java/com/pinkdumbell/cocobob/domain/pet/PetControllerTest.java
  src/test/resources/application.yml
Labels: refactor, feat, chore

#22 [CB-128] BE 반려동물 등록 api 필요함
  src/main/java/com/pinkdumbell/cocobob/domain/pet/dto/PetCreateResponseDto.java
  src/main/resources/application-setting.yml
  src/test/java/com/pinkdumbell/cocobob/domain/pet/PetControllerTest.java
Labels: test, chore

#25 Cb 222 be api 응답 body 통일되지 않음
  src/main/java/com/pinkdumbell/cocobob/common/AwsS3Service.java
  src/main/java/com/pinkdumbell/cocobob/common/ImageService.java
  src/main/java/com/pinkdumbell/cocobob/common/dto/CommonResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/auth/dto/JwtExceptionResponse.java
  src/main/java/com/pinkdumbell/cocobob/domain/auth/filter/JwtExceptionFilter.java
  src/main/java/com/pinkdumbell/cocobob/domain/common/dto/responseDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/PetController.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/PetService.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/UserController.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/dto/UserLoginResponseDto.java
  src/test/java/com/pinkdumbell/cocobob/domain/pet/PetControllerTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/user/UserControllerTest.java
Labels: test, refactor, fix

#30 Cb 222 be api 응답 body 통일되지 않음
  .gitignore
  build.gradle
  src/main/java/com/pinkdumbell/cocobob/config/MailConfig.java
  src/main/java/com/pinkdumbell/cocobob/domain/auth/JwtTokenProvider.java
  src/main/java/com/pinkdumbell/cocobob/domain/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/pinkdumbell/cocobob/domain/auth/filter/JwtExceptionFilter.java
  src/main/java/com/pinkdumbell/cocobob/domain/common/EmailUtil.java
  src/main/java/com/pinkdumbell/cocobob/domain/common/EmailUtilImpl.java
  src/main/java/com/pinkdumbell/cocobob/domain/common/dto/EmailSendResultDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/common/dto/ResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/PetController.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/PetService.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/dto/BreedsInfoResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/User.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/UserController.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/UserService.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/dto/UpdatePasswordRequestDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/dto/UserPasswordRequestDto.java
  src/main/resources/application-setting.yml
  src/test/java/com/pinkdumbell/cocobob/domain/pet/PetControllerTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/user/UserServiceTest.java
  src/test/resources/application.yml
Labels: test, refactor, fix, feat, docs

#31 CB-222 [refactor]: Mocking service test
  src/main/java/com/pinkdumbell/cocobob/domain/user/UserController.java
  src/test/java/com/pinkdumbell/cocobob/domain/pet/PetControllerTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/user/UserControllerTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/user/UserServiceTest.java
Labels: test

#29 [CB-188] [BE] 반려동물 등록 시 사용자와 반려동물을 연관시켜야 함
  src/main/java/com/pinkdumbell/cocobob/common/EmailUtil.java
  src/main/java/com/pinkdumbell/cocobob/common/EmailUtilImpl.java
  src/main/java/com/pinkdumbell/cocobob/common/dto/EmailSendResultDto.java
  src/main/java/com/pinkdumbell/cocobob/common/dto/ResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/config/WebConfig.java
  src/main/java/com/pinkdumbell/cocobob/config/annotation/loginuser/LoginUser.java
  src/main/java/com/pinkdumbell/cocobob/config/annotation/loginuser/LoginUserArgumentResolver.java
  src/main/java/com/pinkdumbell/cocobob/domain/common/EmailUtil.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/Pet.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/PetController.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/PetService.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/User.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/UserService.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/dto/LoginUserInfo.java
  src/test/java/com/pinkdumbell/cocobob/CocobobApplicationTests.java
  src/test/java/com/pinkdumbell/cocobob/domain/pet/PetControllerTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/user/UserControllerTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/user/UserServiceTest.java
  src/test/resources/application.yml
Labels: fix, feat

#32 [CB-226] BE 상품 정보를 제공하는 api 없음
  src/main/java/com/pinkdumbell/cocobob/domain/product/Product.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/ingredient/Ingredient.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/nutrition/Nutrition.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/property/PetProperty.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/property/Property.java
  src/main/resources/db/migration/V3__product.sql
Labels: feat, chore

#33 CB-252 [feat]: available Authorization Button
  src/main/java/com/pinkdumbell/cocobob/config/SwaggerConfig.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/PetController.java
Labels: docs, chore

#34 [CB-226] BE 상품 정보를 제공하는 api 없음
  src/main/resources/db/migration/V4__insert_product_info.sql
Labels: feat, chore

#35 [CB-151] BE 엔터티 생성 수정 삭제일자가 없음
  src/main/java/com/pinkdumbell/cocobob/common/BaseEntity.java
  src/main/java/com/pinkdumbell/cocobob/config/JpaAuditingConfig.java
  src/main/java/com/pinkdumbell/cocobob/domain/daily/Daily.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/Pet.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/User.java
  src/main/resources/db/migration/V5__add_created_updated_at.sql
  src/test/java/com/pinkdumbell/cocobob/domain/user/UserRepositoryTest.java
Labels: test, feat, chore
