Repository PinkDumbbell/CocoBob-BE, pull requests merged in 2022-08, with the labels that each got.

#37 [CB-257] [BE] 사용자 정보를 가져오는 기능이 필요함
  src/main/java/com/pinkdumbell/cocobob/domain/pet/Pet.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/dto/SimplePetInfoDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/image/PetImage.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/User.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/UserController.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/UserRepository.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/UserService.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/dto/UserGetResponseDto.java
  src/test/java/com/pinkdumbell/cocobob/domain/user/UserControllerUnitTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/user/UserRepositoryTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/user/UserServiceUnitTest.java
Labels: test, refactor, feat, chore

#38 [CB-266] BE 반려동물 등록 시 생일과 개월 수에 대한 복합적인 validation이 필요함
  src/main/java/com/pinkdumbell/cocobob/config/annotation/properbirthinfo/ProperBirthInfo.java
  src/main/java/com/pinkdumbell/cocobob/config/annotation/properbirthinfo/ProperBirthInfoValidator.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/PetService.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/dto/PetCreateRequestAgeDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/dto/PetCreateRequestDto.java
  src/test/java/com/pinkdumbell/cocobob/domain/pet/PetControllerTest.java
Labels: test, fix, feat

#39 Cb 226 be 상품 정보를 제공하는 api 없음
  src/main/java/com/pinkdumbell/cocobob/domain/pet/PetService.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/ProductController.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/ProductRepository.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/ProductSearchSpecification.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/ProductService.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/dto/ListProductDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/dto/ProductSpecificSearchDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/UserController.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/UserService.java
  src/test/java/com/pinkdumbell/cocobob/domain/product/ProductControllerTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/product/ProductRepositoryTest.java
Labels: refactor, fix, feat, docs

#40 [CB-173] [BE] 반려동물 정보수정 삭제 불러오기 기능이 필요함
  src/main/java/com/pinkdumbell/cocobob/domain/pet/PetController.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/PetService.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/breed/Breed.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/dto/PetInfoResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/UserRepository.java
  src/test/java/com/pinkdumbell/cocobob/domain/pet/PetControllerTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/pet/PetServiceTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/user/UserRepositoryTest.java
Labels: test, refactor, feat

#41 Cb 226 be 상품 정보를 제공하는 api 없음
  src/main/java/com/pinkdumbell/cocobob/common/dto/CommonResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/common/dto/EmailSendResultDto.java
  src/main/java/com/pinkdumbell/cocobob/common/dto/ResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/dto/BreedsInfoResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/Product.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/ProductSearchSpecification.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/ProductService.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/dto/FindAllResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/dto/ListProductDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/dto/PetPropertyResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/dto/ProductDetailResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/dto/ProductSimpleResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/dto/ProductSpecificSearchDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/property/PetProperty.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/property/PetPropertyRepository.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/property/Property.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/dto/UpdatePasswordRequestDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/dto/UserEmailRequestDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/dto/UserLoginRequestDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/dto/UserLoginResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/dto/UserPasswordRequestDto.java
  src/main/resources/db/migration/V6__merge_product_pet_property.sql
Labels: test, refactor, fix, feat, docs, chore

#42 [CB-173][BE] 반려동물 정보수정 삭제 불러오기 기능이 필요함
  src/main/java/com/pinkdumbell/cocobob/domain/pet/PetController.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/PetRepository.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/PetService.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/dto/BreedsInfoResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/dto/PetDetailResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/exception/ErrorCode.java
  src/test/java/com/pinkdumbell/cocobob/domain/pet/PetControllerTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/pet/PetRepositoryTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/pet/PetServiceTest.java
Labels: test, feat, chore

#43 Cb 285 be query dsl이 적용되지 않음
  build.gradle
  src/main/java/com/pinkdumbell/cocobob/config/QueryDslConfig.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/ProductController.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/ProductPredicate.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/ProductRepository.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/ProductSearchQueryDsl.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/ProductSearchQueryDslImpl.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/ProductService.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/dto/FindAllResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/dto/ProductDetailResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/dto/ProductSimpleResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/dto/ProductSpecificSearchDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/like/Like.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/like/LikeController.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/like/LikeId.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/like/LikeRepository.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/like/LikeService.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/like/dto/LikeRequestDto.java
  src/main/java/com/pinkdumbell/cocobob/exception/ErrorCode.java
  src/test/java/com/pinkdumbell/cocobob/domain/pet/PetRepositoryTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/product/ProductControllerTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/product/ProductRepositoryTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/product/ProductServiceTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/user/UserRepositoryTest.java
Labels: fix, feat, docs, chore

#44 [CB-173] [BE] 반려동물 정보수정 삭제 불러오기 기능이 필요함 - [CB-286]
  src/main/java/com/pinkdumbell/cocobob/common/AwsS3Service.java
  src/main/java/com/pinkdumbell/cocobob/common/ImageService.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/Pet.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/PetController.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/PetService.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/dto/PetUpdateRequestDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/image/PetImageRepository.java
  src/main/java/com/pinkdumbell/cocobob/exception/ErrorCode.java
  src/test/java/com/pinkdumbell/cocobob/domain/pet/PetServiceTest.java
Labels: test, refactor, feat, chore

#45 [CB-137] [CB-299] [BE] 소셜 로그인 기능이 없음
  .github/workflows/deploy.yaml
  build.gradle
  src/main/java/com/pinkdumbell/cocobob/domain/auth/dto/GoogleOAuthRequest.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/AccountType.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/User.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/UserController.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/UserService.java
  src/test/java/com/pinkdumbell/cocobob/CocobobApplicationTests.java
  src/test/java/com/pinkdumbell/cocobob/domain/product/ProductControllerTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/user/UserControllerTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/user/UserServiceTest.java
  src/test/resources/application.yml
Labels: refactor, fix, feat, chore

#47 CB 305 be 데일리 기록 test가 없음
  src/main/java/com/pinkdumbell/cocobob/domain/daily/Daily.java
  src/main/java/com/pinkdumbell/cocobob/domain/daily/DailyController.java
  src/main/java/com/pinkdumbell/cocobob/domain/daily/DailyRepository.java
  src/main/java/com/pinkdumbell/cocobob/domain/daily/DailyService.java
  src/main/java/com/pinkdumbell/cocobob/domain/daily/dto/DailyRecordDetailResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/daily/dto/DailyRecordGetRequestDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/daily/dto/DailyRecordGetResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/daily/dto/DailyRecordRegisterRequestDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/daily/dto/DailyRecordRegisterResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/daily/dto/DailyRecordUpdateRequestDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/daily/dto/DailyRecordUpdateResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/daily/dto/DailySimpleRequestDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/daily/dto/DailySimpleResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/daily/image/DailyImage.java
  src/main/java/com/pinkdumbell/cocobob/domain/daily/image/DailyImageRepository.java
  src/main/java/com/pinkdumbell/cocobob/exception/ErrorCode.java
  src/main/resources/application-setting.yml
  src/test/java/com/pinkdumbell/cocobob/domain/daily/DailyControllerTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/daily/DailyServiceTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/pet/PetServiceTest.java
Labels: test, refactor, fix, docs

#48 CB 309 카카오 로그인 연동
  .github/workflows/deploy.yaml
  src/main/java/com/pinkdumbell/cocobob/domain/auth/GoogleOauthInfo.java
  src/main/java/com/pinkdumbell/cocobob/domain/auth/KakaoOauthInfo.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/UserController.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/UserService.java
Labels: feat, chore

#50 [CB-137] [CB-293] BE 소셜 로그인 기능이 없음
  .github/workflows/deploy.yaml
  build.gradle
  src/main/java/com/pinkdumbell/cocobob/domain/auth/AppleOauthInfo.java
  src/main/java/com/pinkdumbell/cocobob/domain/auth/AppleUtil.java
  src/main/java/com/pinkdumbell/cocobob/domain/auth/dto/AppleOauthRequest.java
  src/main/java/com/pinkdumbell/cocobob/domain/auth/dto/AppleOauthResponse.java
  src/main/java/com/pinkdumbell/cocobob/domain/auth/dto/ApplePublicKeysResponse.java
  src/main/java/com/pinkdumbell/cocobob/domain/auth/dto/AppleRedirectResponse.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/UserController.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/UserService.java
Labels: feat, chore

#51 [CB-137] [CB-293] BE 소셜 로그인 기능이 없음 : 테스트 수정
  src/test/java/com/pinkdumbell/cocobob/CocobobApplicationTests.java
  src/test/java/com/pinkdumbell/cocobob/domain/product/ProductControllerTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/user/UserControllerTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/user/UserControllerUnitTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/user/UserServiceTest.java
Labels: fix

#52 Cb 324 be 상품 추천 기능이 필요함
  src/main/java/com/pinkdumbell/cocobob/domain/pet/PetService.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/ProductController.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/dto/ProductSpecificSearchDto.java
Labels: feat

#54 [CB-137] [CB-293] [BE] 소셜 로그인 기능이 없음
  src/main/java/com/pinkdumbell/cocobob/domain/auth/AppleRefreshToken.java
  src/main/java/com/pinkdumbell/cocobob/domain/auth/AppleRefreshTokenRepository.java
  src/main/java/com/pinkdumbell/cocobob/domain/auth/AppleUtil.java
  src/main/java/com/pinkdumbell/cocobob/domain/auth/dto/DecodedIdTokenAndRefreshTokenDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/UserController.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/UserService.java
  src/main/resources/db/migration/V7__add_apple_refresh_token_table.sql
Labels: refactor, fix, feat, chore

#55 [CB-332] [BE] 사용자 반려동물의 연관관계 때문에 서로 참조하여 삭제할 수 없음
  src/main/java/com/pinkdumbell/cocobob/domain/pet/PetService.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/User.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/dto/UserGetResponseDto.java
  src/main/resources/db/migration/V8__drop_relation_between_user_with_representativepet.sql
Labels: fix, chore

#56 CB-343 [feat]: add browse use wishlist
  src/main/java/com/pinkdumbell/cocobob/domain/product/ProductController.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/ProductService.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/like/LikeRepository.java
Labels: feat

#59 [CB-341] 반려동물 삭제
  src/main/java/com/pinkdumbell/cocobob/domain/pet/Pet.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/PetController.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/PetService.java
  src/main/java/com/pinkdumbell/cocobob/exception/ErrorCode.java
  src/main/resources/db/migration/V10__add_column_brand_to_product.sql
  src/main/resources/db/migration/V11__add_brand_value_and_remove_exp_from_product.sql
  src/main/resources/db/migration/V9.1__add_trigger_event_delete_pet.sql
  src/main/resources/db/migration/V9__add_deleted_column_to_pet.sql
  src/test/java/com/pinkdumbell/cocobob/domain/pet/PetRepositoryTest.java
Labels: test, refactor, feat, docs, chore

#60 [CB-353] [BE] v1 daily api가 필요함
  src/main/java/com/pinkdumbell/cocobob/domain/daily/Daily.java
  src/main/java/com/pinkdumbell/cocobob/domain/daily/DailyController.java
  src/main/java/com/pinkdumbell/cocobob/domain/daily/DailyService.java
  src/main/java/com/pinkdumbell/cocobob/domain/daily/dto/TempDailyDatesResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/daily/dto/TempDailyRequestDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/daily/dto/TempDailyResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/Pet.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/PetController.java
  src/main/java/com/pinkdumbell/cocobob/domain/pet/PetService.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/User.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/dto/UserGetResponseDto.java
  src/main/java/com/pinkdumbell/cocobob/exception/ErrorCode.java
  src/main/resources/db/migration/V10__add_column_brand_to_product.sql
  src/main/resources/db/migration/V11__add_brand_value_and_remove_exp_from_product.sql
  src/main/resources/db/migration/V12__data_column_to_daily.sql
  src/main/resources/db/migration/V8__drop_relation_between_user_with_representativepet.sql
  src/main/resources/db/migration/V9.1__add_trigger_event_delete_pet.sql
  src/main/resources/db/migration/V9__add_deleted_column_to_pet.sql
  src/test/java/com/pinkdumbell/cocobob/domain/daily/DailyControllerTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/daily/DailyServiceTest.java
  src/test/java/com/pinkdumbell/cocobob/domain/pet/PetRepositoryTest.java
Labels: refactor, feat, docs, chore

#62 CB357 be 좋아요 기능 사용시 user id 사용 불필요함
  src/main/java/com/pinkdumbell/cocobob/config/SwaggerConfig.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/like/LikeController.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/like/LikeService.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/like/dto/LikeRequestDto.java
Labels: refactor, docs, chore

#63 [CB-357] 상품 좋아요시 userId 입력 받는 방식을 변경
  src/main/java/com/pinkdumbell/cocobob/config/SwaggerConfig.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/like/LikeController.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/like/LikeService.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/like/dto/LikeRequestDto.java
Labels: refactor, fix, docs, chore

#64 [hotfix]: error handling recommendation product
  src/main/java/com/pinkdumbell/cocobob/domain/product/ProductController.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/dto/ProductSpecificSearchWithLikeDto.java
Labels: fix

#65 [CB-369] fix : 쓸모없는 트리거 삭제
  src/main/resources/db/migration/V13__drop_useless_trigger_when_pet_deleted.sql
Labels: fix

#67 [CB-371] [BE] 대표 반려동물 변경 API가 필요함
  src/main/java/com/pinkdumbell/cocobob/domain/pet/Pet.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/UserController.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/UserService.java
  src/main/java/com/pinkdumbell/cocobob/domain/user/dto/RepresentativePetUpdateDto.java
  src/test/java/com/pinkdumbell/cocobob/domain/user/UserServiceUnitTest.java
Labels: test, feat, docs

#66 Cb 370 상품 키워드 제공 api가 없음
  src/main/java/com/pinkdumbell/cocobob/domain/product/ProductController.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/ProductPredicate.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/ProductSearchQueryDsl.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/ProductSearchQueryDslImpl.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/ProductService.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/dto/ProductKeywordDto.java
  src/main/resources/db/migration/V13__replace_blank_from_proudct_brand.sql
Labels: feat

#68 Cb 370 상품 키워드 제공 api가 없음
  src/main/java/com/pinkdumbell/cocobob/domain/product/ProductController.java
  src/test/java/com/pinkdumbell/cocobob/config/TestConfig.java
  src/test/java/com/pinkdumbell/cocobob/domain/product/ProductRepositoryTest.java
Labels: test, docs
