Repository PinkDumbbell/CocoBob-BE, pull requests merged in 2022-10, with the labels that each got.

#79 [CB-429] [BE] Daily Note 생성 API 리스폰스에 ID가 필요함
  src/main/java/com/pinkdumbell/cocobob/domain/record/daily/DailyController.java
  src/main/java/com/pinkdumbell/cocobob/domain/record/daily/DailyResponseClass.java
  src/main/java/com/pinkdumbell/cocobob/domain/record/daily/DailyService.java
  src/main/java/com/pinkdumbell/cocobob/domain/record/daily/dto/DailyCreateResponseDto.java
Labels: fix

#80 [CB-431] [BE] 날짜에 대한 walk list 불러오기 기능이 필요함
  src/main/java/com/pinkdumbell/cocobob/domain/record/walk/WalkController.java
  src/main/java/com/pinkdumbell/cocobob/domain/record/walk/WalkRepository.java
  src/main/java/com/pinkdumbell/cocobob/domain/record/walk/WalkResponseClass.java
  src/main/java/com/pinkdumbell/cocobob/domain/record/walk/WalkService.java
  src/main/java/com/pinkdumbell/cocobob/domain/record/walk/dto/WalksBriefInfoDto.java
Labels: feat

#81 Cb 439 be 상품 상세페이지에 필요한 브랜드 이미지가 없음
  src/main/java/com/pinkdumbell/cocobob/domain/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/pinkdumbell/cocobob/domain/auth/filter/JwtExceptionFilter.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/Product.java
  src/main/java/com/pinkdumbell/cocobob/domain/product/dto/ProductDetailResponseDto.java
  src/main/resources/db/migration/V14.9__add_brand_image_to_product.sql
Labels: refactor, feat, docs, chore

#83 [CB-457] hotfix : 건강 기록 조회 오류 해결
  src/main/java/com/pinkdumbell/cocobob/domain/record/RecordService.java
Labels: fix

#85 [CB-477] BE 최근 7 개의 몸무게 데이터 추이가 필요함
  src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/HealthRecordController.java
  src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/HealthRecordRepository.java
  src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/HealthRecordResponseClass.java
  src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/HealthRecordService.java
  src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/dto/RecentWeightsPerDatesDto.java
  src/main/java/com/pinkdumbell/cocobob/domain/record/healthrecord/dto/RecentWeightsResponseDto.java
  src/test/java/com/pinkdumbell/cocobob/domain/record/healthrecord/HealthRecordRepositoryTest.java
Labels: test, feat

#86 [CB-127] [BE] 데이터 히스토리 테이블이 없음
  src/main/java/com/pinkdumbell/cocobob/common/apilog/ApiLog.java
  src/main/java/com/pinkdumbell/cocobob/common/apilog/ApiLogInterceptor.java
  src/main/java/com/pinkdumbell/cocobob/common/apilog/ApiLogRepository.java
  src/main/java/com/pinkdumbell/cocobob/config/WebConfig.java
  src/main/resources/db/migration/V15__create_api_log.sql
Labels: feat
